### ISSUE TITLE
[BUG] MANAGE INSTRUMENT --> error message for opening outdate Microscope JSON file is inappropriate

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#468]
**Describe the bug**
Since version beta_0.45.1-b1-0 outdated Microscope.json files should not open and should give a warning.
James Chambers's old microscope file (see attached) displays the expected behavior, however the warning in 

**Desktop (please complete the following information):**
 - OS: [10.15.7](url)
 - Version 1.6.5

**To Reproduce**

- Download the attached Microscope.txt file [chambers_nikon_hca.txt](https://github.com/WU-BIMAC/MicroMetaApp-React/files/7557713/chambers_nikon_hca.txt)
- Save it as JSON
- Move it to the home folder
- Attempt to "Load from the local home folder" file fails as expected but 

ERROR WARNING IS NOT APPROPRIATE
![image](https://user-images.githubusercontent.com/4050585/196287813-1520b192-79de-413f-a3ff-8c7df3bb1861.png)

**Comment by strambc** [comment]
Inherits from #416

**Comment by Akramhar** [comment]
this should be fixed in electron 2.1.0 - react 1.8.0

**Comment by strambc** [comment]
@Akramhar 
The message is still incorrect.
Please change to:

"The Microscope file you are trying to open is no longer supported as it was created based on a deprecated version of the underlying Microscopy Metadata model. To open this file, please use v1.6.15-b1 or earlier."
