### ISSUE TITLE
[FIX] MMA Components library buttons

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#479]
- [ ] "Cancel" button missing box and has spurious ");" text

<img width="170" height="48" alt="Image" src="https://github.com/user-attachments/assets/4639d105-6226-4816-95fd-5bd196a9b13b" />

- [ ]  Remove "+" from "Create Template" button

<img width="191" height="48" alt="Image" src="https://github.com/user-attachments/assets/970e1ce3-056d-48bf-886c-b442fc11f80c" />

**Comment by Akramhar** [comment]
should be fixed in MMA 1.8.1

**Comment by strambc** [comment]
Box around the "Cancel" button in still missing

<img width="679" height="102" alt="Image" src="https://github.com/user-attachments/assets/8eaa688e-bf67-447a-8504-b9774544b356" />

**Comment by Akramhar** [comment]
should be solved in mma 1.8.2, explorer 1.1.2, mmt 2.2.2
